### ISSUE TITLE
Game Saves Aren't Persistent Through Reboots/Shutdowns

### ISSUE THREAD

**Issue by emTr0** [a7omic/snes9x-pb#4]
Game saves only save while snes9x is open but after it is shutdown or otherwise closed (reboots), saves are erased.

**Comment by a7omic** [comment]
This is not the case for me.  I have save games for Crono Trigger that have persisted.  What rom are you playing?  You are saving using the games saving mechanism?

**Comment by a7omic** [comment]
If you were cycling to the next rom before closing the app then yes the save game would not persist.  If you closed the app from the game you just saved then it would persist.  I added a new version to the downloads that resolves this, can you try it and let me know if it resolves your issue.

**Comment by emTr0** [comment]
Saves persist with the new version. Thank you.
