### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by arlanda** [a7omic/snes9x-pb#8]
Please: 
1) add support that will allow us to use bluetooth controller instead of touchscreen (i.e. PS3 six axis, Xbox controller, Gametel’s Gamepad, keyboard, etc.)
2) add an option to hide the touchscreen controller if playing with regular controller in hand
3) ROM list instead of cycle

Thanks!

**Comment by a7omic** [comment]
I am not taking feature requests, if you want something please feel free to fork the code and implement it yourself.
